Repository buggregator/app, pull requests merged in 2022-07, with the labels that each got.

#80 Added example mysql configuration
  .env.example
Labels: documentation

#82 Show all event's exceptions
  resources/js/Components/Sentry/Show/Exception.vue
  resources/js/Components/Sentry/Show/Exceptions.vue
  resources/js/Pages/Sentry/Show.vue
  resources/js/Sentry/event.js
Labels: enhancement, improvement

#83 Fix tags not showing issue
  resources/js/Sentry/event.js
Labels: bug

#85 Show event's user data
  resources/js/Components/Sentry/Show/User.vue
  resources/js/Pages/Sentry/Show.vue
  resources/js/Sentry/event.js
Labels: enhancement, improvement

#84 Showing custom tags
  resources/js/Components/Sentry/Show/Tags.vue
  resources/js/Sentry/event.js
Labels: enhancement, improvement

#86 Show event's contexts
  resources/js/Components/Sentry/Show/App.vue
  resources/js/Components/Sentry/Show/Device.vue
  resources/js/Components/Sentry/Show/OS.vue
  resources/js/Pages/Sentry/Show.vue
  resources/js/Sentry/event.js
Labels: enhancement, improvement

#81 Show event transaction name
  resources/js/Components/Sentry/Payloads/Exception.vue
  resources/js/Event.js
  resources/scss/components/events/list-page/event-sentry.scss
Labels: enhancement, improvement

#90 Fixes cs
  app/Application/Domain/Entity/ExtendedTypecast.php
  app/Infrastructure/CycleOrm/Database/Drivers/SQLiteDriver.php
  app/Modules/Events/Application/Queries/FindEventByUuid/Handler.php
  app/Modules/User/Domain/Events/UserWasCreated.php
Labels: improvement

#93 Fix/default database
  .env.example
  Dockerfile
  docker-compose.yml
  docker/server/startup.sh
  package-lock.json
  public/mix-manifest.json
Labels: bug, improvement

#95 Add tag 'beta' for docker builds with for pre releases
  .github/workflows/docker-image-beta.yml
  README.md
Labels: documentation, improvement, usability
